
import java.awt.Color;
import javax.swing.JFrame;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Cherini
 */
public class Urna extends javax.swing.JFrame {

    public int candidato111 = 0;
    public int candidato101 = 0;
    public int candidato010 = 0;
    public int votosEmBranco = 0;
    public String selectCand = "";
    public int digVote = 1;
    
    
    /**
     * Creates new form Urna
     */
    public Urna() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        confirma = new javax.swing.JButton();
        jButton0 = new javax.swing.JButton();
        white = new javax.swing.JButton();
        corrige = new javax.swing.JButton();
        descricao = new javax.swing.JLabel();
        descricao1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        contri1 = new javax.swing.JLabel();
        number1 = new javax.swing.JTextField();
        number2 = new javax.swing.JTextField();
        obsone = new javax.swing.JLabel();
        foto = new javax.swing.JLabel();
        contribuicao = new javax.swing.JLabel();
        obsOne = new javax.swing.JLabel();
        obs = new javax.swing.JLabel();
        obsTwo = new javax.swing.JLabel();
        number3 = new javax.swing.JTextField();
        nome1 = new javax.swing.JLabel();
        jOptionPane1 = new javax.swing.JOptionPane();
        jOptionPane2 = new javax.swing.JOptionPane();
        toVote = new javax.swing.JLabel();

        jLabel5.setText("Voto Para:");

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(218, 216, 211));
        jPanel1.setLayout(null);

        jButton1.setBackground(new java.awt.Color(26, 25, 25));
        jButton1.setFont(new java.awt.Font("Segoe UI Light", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(236, 236, 236));
        jButton1.setText("1");
        jButton1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton1.setPreferredSize(new java.awt.Dimension(120, 100));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(90, 50, 70, 50);

        jButton3.setBackground(new java.awt.Color(26, 25, 25));
        jButton3.setFont(new java.awt.Font("Segoe UI Light", 1, 24)); // NOI18N
        jButton3.setForeground(new java.awt.Color(236, 236, 236));
        jButton3.setText("3");
        jButton3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton3.setPreferredSize(new java.awt.Dimension(120, 100));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(270, 50, 70, 50);

        jButton2.setBackground(new java.awt.Color(26, 25, 25));
        jButton2.setFont(new java.awt.Font("Segoe UI Light", 1, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(236, 236, 236));
        jButton2.setText("2");
        jButton2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton2.setPreferredSize(new java.awt.Dimension(120, 100));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(180, 50, 70, 50);

        jButton6.setBackground(new java.awt.Color(26, 25, 25));
        jButton6.setFont(new java.awt.Font("Segoe UI Light", 1, 24)); // NOI18N
        jButton6.setForeground(new java.awt.Color(236, 236, 236));
        jButton6.setText("6");
        jButton6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton6.setPreferredSize(new java.awt.Dimension(120, 100));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6);
        jButton6.setBounds(270, 120, 70, 50);

        jButton5.setBackground(new java.awt.Color(26, 25, 25));
        jButton5.setFont(new java.awt.Font("Segoe UI Light", 1, 24)); // NOI18N
        jButton5.setForeground(new java.awt.Color(236, 236, 236));
        jButton5.setText("5");
        jButton5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton5.setPreferredSize(new java.awt.Dimension(120, 100));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);
        jButton5.setBounds(180, 120, 70, 50);

        jButton4.setBackground(new java.awt.Color(26, 25, 25));
        jButton4.setFont(new java.awt.Font("Segoe UI Light", 1, 24)); // NOI18N
        jButton4.setForeground(new java.awt.Color(236, 236, 236));
        jButton4.setText("4");
        jButton4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton4.setPreferredSize(new java.awt.Dimension(120, 100));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(90, 120, 70, 50);

        jButton8.setBackground(new java.awt.Color(26, 25, 25));
        jButton8.setFont(new java.awt.Font("Segoe UI Light", 1, 24)); // NOI18N
        jButton8.setForeground(new java.awt.Color(236, 236, 236));
        jButton8.setText("8");
        jButton8.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton8.setPreferredSize(new java.awt.Dimension(120, 100));
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton8);
        jButton8.setBounds(180, 190, 70, 50);

        jButton7.setBackground(new java.awt.Color(26, 25, 25));
        jButton7.setFont(new java.awt.Font("Segoe UI Light", 1, 24)); // NOI18N
        jButton7.setForeground(new java.awt.Color(236, 236, 236));
        jButton7.setText("7");
        jButton7.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton7.setPreferredSize(new java.awt.Dimension(120, 100));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7);
        jButton7.setBounds(90, 190, 70, 50);

        jButton9.setBackground(new java.awt.Color(26, 25, 25));
        jButton9.setFont(new java.awt.Font("Segoe UI Light", 1, 24)); // NOI18N
        jButton9.setForeground(new java.awt.Color(236, 236, 236));
        jButton9.setText("9");
        jButton9.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton9.setPreferredSize(new java.awt.Dimension(120, 100));
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton9);
        jButton9.setBounds(270, 190, 70, 50);

        confirma.setBackground(new java.awt.Color(0, 153, 0));
        confirma.setFont(new java.awt.Font("Segoe UI Light", 1, 12)); // NOI18N
        confirma.setForeground(new java.awt.Color(28, 28, 28));
        confirma.setText("CONFIRMA");
        confirma.setToolTipText("");
        confirma.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        confirma.setEnabled(false);
        confirma.setPreferredSize(new java.awt.Dimension(60, 40));
        confirma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmaActionPerformed(evt);
            }
        });
        jPanel1.add(confirma);
        confirma.setBounds(280, 290, 70, 100);

        jButton0.setBackground(new java.awt.Color(26, 25, 25));
        jButton0.setFont(new java.awt.Font("Segoe UI Light", 1, 24)); // NOI18N
        jButton0.setForeground(new java.awt.Color(236, 236, 236));
        jButton0.setText("0");
        jButton0.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton0.setPreferredSize(new java.awt.Dimension(120, 100));
        jButton0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton0ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton0);
        jButton0.setBounds(180, 260, 70, 50);

        white.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        white.setForeground(new java.awt.Color(28, 28, 28));
        white.setText("BRANCO");
        white.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        white.setPreferredSize(new java.awt.Dimension(60, 40));
        white.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                whiteMouseClicked(evt);
            }
        });
        white.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                whiteActionPerformed(evt);
            }
        });
        jPanel1.add(white);
        white.setBounds(80, 350, 90, 40);

        corrige.setBackground(new java.awt.Color(153, 0, 0));
        corrige.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        corrige.setForeground(new java.awt.Color(28, 28, 28));
        corrige.setText("CORRIGE");
        corrige.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        corrige.setPreferredSize(new java.awt.Dimension(60, 40));
        corrige.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                corrigeActionPerformed(evt);
            }
        });
        jPanel1.add(corrige);
        corrige.setBounds(180, 350, 90, 40);

        descricao.setText("Desenvolvido por Giordano C. Cherini - E-mail: giordanocherini@gmail.com");
        jPanel1.add(descricao);
        descricao.setBounds(10, 20, 420, 20);

        descricao1.setText("Sistema de Contagem de Voto - S I M U L A D O R - Para fins Educacionais.");
        jPanel1.add(descricao1);
        descricao1.setBounds(10, 0, 420, 20);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(720, 0, 440, 400);

        jPanel2.setBackground(new java.awt.Color(218, 216, 211));

        contri1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N

        number1.setEditable(false);
        number1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        number1.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        number2.setEditable(false);
        number2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        number2.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        obsone.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N

        contribuicao.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        contribuicao.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        obsOne.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        obsOne.setForeground(new java.awt.Color(51, 51, 51));

        obs.setFont(new java.awt.Font("Segoe UI", 3, 16)); // NOI18N
        obs.setForeground(new java.awt.Color(51, 51, 51));
        obs.setText("Digite o número correspondente para finalizar seu voto.");

        obsTwo.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        obsTwo.setForeground(new java.awt.Color(51, 51, 51));

        number3.setEditable(false);
        number3.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        number3.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        nome1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N

        jOptionPane1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jOptionPane1.setMessage("      N° VOTOS");
        jOptionPane1.setFont(new java.awt.Font("Segoe UI Light", 3, 14)); // NOI18N
        jOptionPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jOptionPane1MouseClicked(evt);
            }
        });

        jOptionPane2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jOptionPane2.setMessage("   CANDIDATOS");
        jOptionPane2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jOptionPane2.setFont(new java.awt.Font("Segoe UI Light", 3, 14)); // NOI18N
        jOptionPane2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jOptionPane2MouseClicked(evt);
            }
        });

        toVote.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        toVote.setForeground(new java.awt.Color(51, 51, 51));
        toVote.setText("<html>Vote para decidir quem foi o \"pai\" da COMPUTAÇÃO:</html>");
        toVote.setToolTipText("");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(obsOne, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(obsTwo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(obsone, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(0, 0, Short.MAX_VALUE))))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(46, 46, 46)
                            .addComponent(number1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(number2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(12, 12, 12)
                            .addComponent(number3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(nome1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(contri1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(contribuicao, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(obs, javax.swing.GroupLayout.PREFERRED_SIZE, 469, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(toVote, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(foto, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15))
                    .addComponent(jOptionPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jOptionPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(toVote, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(number1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(number2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(number3, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(8, 8, 8)
                                .addComponent(nome1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(contri1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(0, 167, Short.MAX_VALUE)
                                .addComponent(contribuicao, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(foto, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(obs, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(obsOne, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(obsone)
                                .addGap(10, 10, 10)
                                .addComponent(obsTwo, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jOptionPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addComponent(jOptionPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 710, 400);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        numChange("1");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void numChange(String numero) {
          selectCand+=numero;
          foto.setIcon(new javax.swing.ImageIcon(getClass().getResource("")));
          obs.setText("");
          toVote.setText("<html>Vote para decidir quem foi o \"pai\" da COMPUTAÇÃO:</html>");

          if(digVote < 3){
              if(digVote == 1) {
                number1.setText(numero);
              } else if(digVote == 2) {
                number2.setText(numero);
              } 
          }
          else if(digVote == 3){
              number3.setText(numero);
              obsOne.setForeground(Color.red);
              
              switch(selectCand) {
                    case "111":
                        this.getCandidato("John Von Neumann", "Ter formalizado o projeto lógico de um computador. <br/>Em sua proposta, sugeriu que as instruções fossem armazenadas na memória do computador.", "JN.jpg");
                        break;
                    case "101":
                        this.getCandidato("Alan Turing", "Um modelo teórico que pode ser usado para implementar todos os aspectos lógicos e matemáticos de um computador.", "AT.jpg");
                        break;
                    case "010":
                        this.getCandidato("Charles Babbage", "Referenciado como o inventor que projetou o primeiro computador de uso geral, utilizando apenas partes mecânicas, a máquina analítica.", "CB.jpg");
                        break;
                }
            }  
            digVote ++;
    }
            
    
    private void getCandidato(String nome, String descricao, String imagem) {
                     contribuicao.setText("<html>" + descricao + "</html>");
                     contribuicao.setVisible(true);
                     nome1.setVisible(true);
                     contri1.setVisible(true);
                     obsOne.setVisible(true);
                     obsTwo.setVisible(true);
                     nome1.setText("<html>Nome:&nbsp;&nbsp;" + nome + " </html>");
                     contri1.setText("<html>Contribuição:</html>");
                     obs.setText("Aperte no VERDE para confirmar o voto.");
                     obsOne.setText("Aperte o botão VERMELHO para corrigir o voto.");
                     obsTwo.setText("Aperte o botão BRANCO para votar em branco.");
                     foto.setVisible(true);
                     foto.setIcon(new javax.swing.ImageIcon(getClass().getResource(imagem)));
                     confirma.setEnabled(true);
    }
    
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        numChange("3");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        numChange("2");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        numChange("6");
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        numChange("5");
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        numChange("4");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        numChange("8");
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        numChange("7");
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        numChange("9");
    }//GEN-LAST:event_jButton9ActionPerformed

    private void whiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_whiteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_whiteActionPerformed

    private void jButton0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton0ActionPerformed
        numChange("0");
    }//GEN-LAST:event_jButton0ActionPerformed

        
    private void whiteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_whiteMouseClicked
          selectCand = "";  
          obs.setText("VOCÊ VOTOU EM BRANCO");
          votosEmBranco++;
          toVote.setText("");
          foto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/branco.png"))); 
          nome1.setVisible(false);
          number1.setText("");
          number2.setText("");
          number3.setText("");
          contribuicao.setVisible(false);
          contri1.setVisible(false);
          obs.setVisible(true);
          obsOne.setVisible(false);
          obsTwo.setVisible(false);
          digVote = 1;
    }//GEN-LAST:event_whiteMouseClicked

    private void confirmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmaActionPerformed
        switch(selectCand) {
            case "111":
                        candidato111++;
                        break;
                    case "101":
                        candidato101++;
                        break;
                    case "010":
                        candidato010++;
                        break;
        }
        obs.setText("Voto computado com sucesso.");
        selectCand = "";
        toVote.setText("");
        number1.setText("");
        number2.setText("");
        number3.setText("");
        nome1.setVisible(false);
        contribuicao.setVisible(false);
        contri1.setVisible(false);
        obsOne.setVisible(false);
        obsTwo.setVisible(false);
        foto.setIcon(new javax.swing.ImageIcon(getClass().getResource("")));
        confirma.setEnabled(false);
        digVote = 1;
        
        
    }//GEN-LAST:event_confirmaActionPerformed

    private void corrigeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_corrigeActionPerformed
        selectCand = "";
        number1.setText("");
        number2.setText("");
        number3.setText("");
        nome1.setVisible(false);
        contribuicao.setVisible(false);
        contri1.setVisible(false);
        obs.setVisible(true);
        obsOne.setVisible(false);
        obsTwo.setVisible(false);
        foto.setIcon(new javax.swing.ImageIcon(getClass().getResource("")));
        confirma.setEnabled(false);
        digVote = 1;
    }//GEN-LAST:event_corrigeActionPerformed

    private void jOptionPane2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jOptionPane2MouseClicked
        // TODO add your handling code here:
        jOptionPane1.showMessageDialog(null,"Candidatos: \n Alan Turing (101).\n John Von Neumann (111).\n Charles Babbage (010) ");
    }//GEN-LAST:event_jOptionPane2MouseClicked

    private void jOptionPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jOptionPane1MouseClicked
        // TODO add your handling code here:
        jOptionPane1.showMessageDialog(null,"Alan Turing: " + candidato101 + " votos.\n" + "John Von Neumann: " + candidato111 + " votos.\n" + "Charles Babbage: " + candidato010 + " votos.\n" + "Votos em Branco: " + votosEmBranco + " votos.\n");
    }//GEN-LAST:event_jOptionPane1MouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        setSize(1170, 439);
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Urna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Urna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Urna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Urna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Urna().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton confirma;
    private javax.swing.JLabel contri1;
    private javax.swing.JLabel contribuicao;
    private javax.swing.JButton corrige;
    private javax.swing.JLabel descricao;
    private javax.swing.JLabel descricao1;
    private javax.swing.JLabel foto;
    private javax.swing.JButton jButton0;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JOptionPane jOptionPane1;
    private javax.swing.JOptionPane jOptionPane2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel nome1;
    private javax.swing.JTextField number1;
    private javax.swing.JTextField number2;
    private javax.swing.JTextField number3;
    private javax.swing.JLabel obs;
    private javax.swing.JLabel obsOne;
    private javax.swing.JLabel obsTwo;
    private javax.swing.JLabel obsone;
    private javax.swing.JLabel toVote;
    private javax.swing.JButton white;
    // End of variables declaration//GEN-END:variables
}
